version: "2.3"

services:
  web:
    image: netmist/dataset_labeling:0.5
    build: .
    volumes:
      - ${IMAGES_PATH}:/opt/static/images
      - ${HUMAN_ANNOTATIONS_PATH}:/opt/static/human_annotations
      - ${MODEL_ANNOTATIONS_PATH}:/opt/static/model_annotations
      - ./config.yml:/opt/config.yml
    ports:
      - 5000:5000
    user: 1000:1000
    command: python3 app.py
